### ISSUE TITLE
Can't open the app if subscription has expired

### ISSUE THREAD

**Issue by y-x41** [etesync/ios#21]
Etesync offers associate accounts:
"Associate accounts are a way for users of EteSync to let non-users view and edit their journals without needing to pay for their own EteSync account. For example, sharing your calendar with your spouse."

You thus should be able to login without an active subscription, since there's a chance somebody has shared calendars with you which you'd like to see on your mobile phone.

The error message is: "Your subscription has been cancelled, please check your dashboard."

**Comment by tasn** [comment]
Associate accounts work, I just tested them. What you are suggesting is in essence for accounts to be automatically downgraded to associates if the subscription expires? Or am I misunderstanding something.

If you have an account that you would like to make an associate, just email support, and we'll fix that for you.

Unrelated to the above, there's a real issue here indeed. The app doesn't gracefully handle subscription expiration. I'm taking a look at it now.

**Comment by y-x41** [comment]
Okay, so like I mentioned in my reply in #17: Signing in works fine for me, I don't know why I said that it doesn't. It's when I hit the update button that I get the error message about the expired subscription.

**Comment by tasn** [comment]
I now fixed it. When it errors you should click "reload the app" and then when you try again, it should gracefully handle errors and show them to you.
It will still however not fetch the data, because this is unfortunately how the server works at the moment. We are working on fixing on it as part of our next protocol update.

For specific help with accessing your data (if you got locked out), please reach out support by email and we will help you out!
